version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "5000:5000"
        volumes:
            - "/usr/src/app/node_modules"
            - ".:/usr/src/app"
    mongo:
        image: mongo
        ports:
            - "27017:27017"
